name: Releasing

on:
  push:
    tags: "v*.*.*"

jobs:
  ffi:
    name: Build backend bin
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - uname: x86-64 Windows
            target: x86_64-pc-windows-gnu
            binName: hello-world.exe
            releaseName: hello-world-x86_64.exe

          - uname: x86 Windows
            target: i686-pc-windows-gnu
            binName: hello-world.exe
            releaseName: hello-world-i686.exe

          - uname: x86-64 Linux
            target: x86_64-unknown-linux-gnu
            binName: hello-world
            releaseName: hello-world.x86_64

          - uname: x86 Linux
            target: i686-unknown-linux-gnu
            binName: hello-world
            releaseName: hello-world.i686

          - uname: ARM64 Linux
            target: aarch64-unknown-linux-gnu
            binName: hello-world
            releaseName: hello-world.aarch64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true

      - name: Build for ${{ matrix.platform.uname }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.platform.target }}
          use-cross: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.binName }}
          name: ${{ matrix.platform.releaseName }}

  release:
    needs: ffi
    name: Release all project binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Prepare artifact dir
        run: mkdir dist

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Create release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            dist/hello-world*
          generate_release_notes: true
